# image: ana-root  # no need to specify explicitly

# services:  # no specific services
    # -

before_script:
    - source activate snake  # activate Snakemake
    - kinit kgizdov -k -t /root/my.keytab  # login to kerberos

# after_script:
    # - echo 'ALL DONE'

# cache:
#     paths:
#         - analysis/bin
#         - common/lib

stages:
        - build
        - plot
        # - test  # not yet implemented

build:
    stage: build
    script:
        - snakemake build -p --cores
    # only:  # run only on these
        # - master
    # except:  # skip branches
        # - /^.*-test$/  # all named *-test
    # tags:  # specify CI runner by tags
        # -
    artifacts:  # use this to retain files
        paths:
            - analysis/bin
            - common/lib

plot_b:
    stage: plot
    script:
        - snakemake b_plots -p --cores
    cache:
        paths:
            - analysis/bin
            - common/lib
    # only:
        # - master
    artifacts:
        paths:
            - plots/comparison/B

# plot_b_pt:
#     stage: plot
#     script:
#         - snakemake b_pt_plots -p --cores
#     cache:
#         paths:
#             - analysis/bin
#             - common/lib
#     only:
#         - master
#     artifacts:
#         paths:
#             - plots/comparison/B

plot_jp:
    stage: plot
    script:
        - snakemake jp_plots -p --cores
    cache:
        paths:
            - analysis/bin
            - common/lib
    only:
        - master
    artifacts:
        paths:
            - plots/comparison/JP

# plot_jp_pt:
#     stage: plot
#     script:
#         - snakemake jp_pt_plots -p --cores
#     cache:
#         paths:
#             - analysis/bin
#             - common/lib
#     only:
#         - master
#     artifacts:
#         paths:
#             - plots/comparison/JP

plot_mu:
    stage: plot
    script:
        - snakemake mu_plots -p --cores
    cache:
        paths:
            - analysis/bin
            - common/lib
    only:
        - master
    artifacts:
        paths:
            - plots/comparison/MU

# plot_mu_pt:
#     stage: plot
#     script:
#         - snakemake mu_pt_plots -p --cores
#     cache:
#         paths:
#             - analysis/bin
#             - common/lib
#     only:
#         - master
#     artifacts:
#         paths:
#             - plots/comparison/MU

plot_om:
    stage: plot
    script:
        - snakemake om_plots -p --cores
    cache:
        paths:
            - analysis/bin
            - common/lib
    only:
        - master
    artifacts:
        paths:
            - plots/comparison/OM

# plot_om_pt:
#     stage: plot
#     script:
#         - snakemake om_pt_plots -p --cores
#     cache:
#         paths:
#             - analysis/bin
#             - common/lib
#     only:
#         - master
#     artifacts:
#         paths:
#             - plots/comparison/OM

plot_pi:
    stage: plot
    script:
        - snakemake pi_plots -p --cores
    cache:
        paths:
            - analysis/bin
            - common/lib
    only:
        - master
    artifacts:
        paths:
            - plots/comparison/PI

# plot_pi_pt:
#     stage: plot
#     script:
#         - snakemake pi_pt_plots -p --cores
#     cache:
#         paths:
#             - analysis/bin
#             - common/lib
#     only:
#         - master
#     artifacts:
#         paths:
#             - plots/comparison/PI

plot_pz:
    stage: plot
    script:
        - snakemake pz_plots -p --cores
    cache:
        paths:
            - analysis/bin
            - common/lib
    only:
        - master
    artifacts:
        paths:
            - plots/comparison/PZ

# plot_pz_pt:
#     stage: plot
#     script:
#         - snakemake pz_pt_plots -p --cores
#     cache:
#         paths:
#             - analysis/bin
#             - common/lib
#     only:
#         - master
#     artifacts:
#         paths:
#             - plots/comparison/PZ
