# image: ana-root  # no need to specify explicitly

# services:  # no specific services
    # -

before_script:
    - source activate snake  # activate Snakemake
    - kinit kgizdov -k -t /root/my.keytab  # login to kerberos

# after_script:
    # - echo 'ALL DONE'

cache:
    paths:
        - analysis/bin
        - common/lib

stages:
        - build
        - plot
        # - test  # not yet implemented

build:
    stage: build
    script:
        - snakemake --cores build
    cache:
        paths:
            - analysis/bin
            - common/lib
    # only:  # run only on these
        # - master
    # except:  # skip branches
        # - /^.*-test$/  # all named *-test
    # tags:  # specify CI runner by tags
        # -
    # artifacts:  # use this to retain files
    #     paths:
    #         - plots/comparison

plot_b:
    stage: plot
    script:
        - snakemake --cores b_plots
    cache:
        paths:
            - analysis/bin
            - common/lib
    # only:
        # - master
    artifacts:
        paths:
            - plots/comparison/B

plot_b_pt:
    stage: plot
    script:
        - snakemake --cores b_pt_plots
    cache:
        paths:
            - analysis/bin
            - common/lib
    only:
        - master
    artifacts:
        paths:
            - plots/comparison/B

plot_jp:
    stage: plot
    script:
        - snakemake --cores jp_plots
    cache:
        paths:
            - analysis/bin
            - common/lib
    only:
        - master
    artifacts:
        paths:
            - plots/comparison/JP

plot_jp_pt:
    stage: plot
    script:
        - snakemake --cores jp_pt_plots
    cache:
        paths:
            - analysis/bin
            - common/lib
    only:
        - master
    artifacts:
        paths:
            - plots/comparison/JP

plot_om:
    stage: plot
    script:
        - snakemake --cores om_plots
    cache:
        paths:
            - analysis/bin
            - common/lib
    only:
        - master
    artifacts:
        paths:
            - plots/comparison/OM

plot_om_pt:
    stage: plot
    script:
        - snakemake --cores om_pt_plots
    cache:
        paths:
            - analysis/bin
            - common/lib
    only:
        - master
    artifacts:
        paths:
            - plots/comparison/OM

plot_pz:
    stage: plot
    script:
        - snakemake --cores pz_plots
    cache:
        paths:
            - analysis/bin
            - common/lib
    only:
        - master
    artifacts:
        paths:
            - plots/comparison/PZ

plot_pz_pt:
    stage: plot
    script:
        - snakemake --cores pz_pt_plots
    cache:
        paths:
            - analysis/bin
            - common/lib
    only:
        - master
    artifacts:
        paths:
            - plots/comparison/PZ
